PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?term ?deprecated
WHERE {
  ?term rdf:type owl:Class .
  OPTIONAL {
      ?term owl:deprecated ?deprecated .
  }
  FILTER(isIRI(?term))
}