### For Disease Ontology, we are interested in all terms
SELECT DISTINCT ?term
WHERE {
  { 
    { 
     ?s1 ?p1 ?term . 
     ?term rdfs:subClassOf* <http://purl.obolibrary.org/obo/DOID_4> .
    }
    UNION
    { 
      ?term ?p2 ?o2 . 
      ?term rdfs:subClassOf* <http://purl.obolibrary.org/obo/DOID_4> .
    }
  }
  FILTER(isIRI(?term))
}
