PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


### All diseases
SELECT DISTINCT ?term ?label ?deprecated
WHERE {
  { 
    { 
     ?s1 ?p1 ?term . 
     ?term rdfs:subClassOf* <http://id.who.int/icd/entity/455013390> .
     OPTIONAL {
       ?term rdfs:label ?label
     }
     OPTIONAL {
       ?term owl:deprecated ?deprecated
     }
    }
    UNION
    { 
      ?term ?p2 ?o2 . 
      ?term rdfs:subClassOf* <http://id.who.int/icd/entity/455013390> .
      OPTIONAL {
        ?term rdfs:label ?label
      }
      OPTIONAL {
        ?term owl:deprecated ?deprecated
      }
    }
  }
  FILTER(isIRI(?term))
}
