PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?class ?exact_match
WHERE {
  ?class a owl:Class ;
         owl:deprecated true ;
         skos:exactMatch ?exact_match .
}
