PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix IAO: <http://purl.obolibrary.org/obo/IAO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT distinct ?sub_o1 ?sub_o2 ?super_o1 ?super_o2 ?sub #?source

WHERE 
{
  	?sub_o1 rdfs:subClassOf* <http://purl.obolibrary.org/obo/MONDO_0000001> ;
        rdfs:subClassOf ?super_o1 .
    ?sub_o2 a owl:Class ;
  		rdfs:subClassOf* <http://www.orpha.net/ORDO/Orphanet_377788> ;
      rdfs:subClassOf ?super_o2 .
  	?sub_o1 skos:exactMatch ?sub_o2 .
  	?super_o1 skos:exactMatch ?super_o2 .
   	?xref_anno a owl:Axiom ;
            owl:annotatedSource ?sub_o1 ;
            owl:annotatedProperty rdfs:subClassOf ;
            owl:annotatedTarget ?super_o1 ;
            oboInOwl:source ?source .
  
  FILTER(STRSTARTS(str(?source), "Orphanet:"))
  
  FILTER NOT EXISTS {
   	?sub_o2 rdfs:subClassOf ?super_o2 .
  }
 #  FILTER(regex(str(?sub),"Orpha"))
  FILTER( !isBlank(?sub_o1) && !isBlank(?sub_o2) && !isBlank(?super_o1) && !isBlank(?super_o2))
} LIMIT 20
