PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# For NCIT, we are only interested in the Neoplasm branch
SELECT DISTINCT ?term
WHERE {
VALUES ?roots {<http://purl.obolibrary.org/obo/NCIT_C3262> <http://purl.obolibrary.org/obo/NCIT_C134533>}
  {
    {
     ?s1 ?p1 ?term .
     ?term rdfs:subClassOf* ?roots .
    }
    UNION
    {
      ?term ?p2 ?o2 .
      ?term rdfs:subClassOf* ?roots .
    }

  }
  FILTER(isIRI(?term))
}
