PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xref: <http://www.geneontology.org/formats/oboInOwl#hasDbXref>


# For ORPHANET, we are only interested in the Disease branch
SELECT DISTINCT ?term
WHERE {
  { 
    { 
     ?s1 ?p1 ?term .
     ?term rdfs:subClassOf* <http://www.orpha.net/ORDO/Orphanet_377788> .
     FILTER NOT EXISTS {
       ?term xref: ?xref .
       FILTER(STRSTARTS(str(?xref),"HGNC:"))
     }
     FILTER(isIRI(?term))
    }
    UNION
    { 
      ?term ?p2 ?o2 .
      ?term rdfs:subClassOf* <http://www.orpha.net/ORDO/Orphanet_377788> .
      FILTER NOT EXISTS {
        ?term xref: ?xref .
        FILTER(STRSTARTS(str(?xref),"HGNC:"))
      }
      FILTER(isIRI(?term))
    }
  }
  
}
